### PR TITLE
feat: update project to Angular v17

### PR DESCRIPTION
**Pull request by bartadaniel**
Hi! I found your lib and I think it deserves being fresh. :) As I currently need it to be compatible, this PR updates to Angular 17. Once merged and published to npm, I can update to 18. 

- Updated dependencies to Angular v17
- Updated polyfills usage to the new format
- Refactored code to comply with new ts checks

### CODE REVIEW

**Comment by bartadaniel** [comment]
Due to lack of response, I made [a fork](https://github.com/bartadaniel/ngx-drag-resize2). Updated the project to v18

**Comment by dmytro-parfenov** [comment]
@bartadaniel Sorry for the late response and thank you for your contribution. Since now, library has been migrated to Angular v19.

**Comment by dmytro-parfenov** [comment]
> hi @dmytro-parfenov! Glad you're back! Do you anticipate having the time to maintain the project? I am open to discontinue my fork, however, I must make sure this lib stays up-to-date and will not block an update on my side in the future. Are you open to accept maintainers for this project, in case your availability changes? Also, in my fork I made a change in `ngxResizeAspectRatio` as I had some issues on how it was before. I don't really remember the specifics though.

Hi! Yes, I am going to maintain the project, at least by keeping actual Angular version. Sure, will accept maintainers in case I am busy.

It would be nice if you could recall what was changed with `ngxResizeAspectRatio` 😉

> 

> 

>

**Review by dmytro-parfenov — COMMENTED** [review]
Closed due to https://github.com/dmytro-parfenov/ngx-drag-resize/pull/6#issuecomment-2491495505

**Pull request closed without merging**
